-- H2: seed editorial field definitions.
-- Scope: DML seed only. Remote apply requires explicit JIT DML approval.
-- No backfill, Pro apply, writers, schedules, canaries, deploys, push, PR, or merge.

INSERT INTO public.editorial_field_definitions (
    field_key,
    target_column,
    ownership,
    is_required_for_publish,
    is_public,
    description
) VALUES
    ('name', 'courses.name', 'hybrid_manual_preferred', true, true, 'Public course title. Required for publication.'),
    ('institution', 'courses.institution_id', 'pipeline_owned', true, true, 'Owning institution reference. Required for publication.'),
    ('url', 'courses.url', 'pipeline_owned', true, true, 'Canonical source URL. Required for publication and deduplication.'),
    ('slug', 'courses.slug', 'pipeline_owned', true, true, 'Public routing slug. Required for publication.'),
    ('category', 'courses.category_id', 'hybrid_manual_preferred', true, true, 'Editorial category used for filters and ROI context. Required for publication.'),
    ('mode', 'courses.mode', 'hybrid_manual_preferred', true, true, 'Delivery mode shown to users. Required for publication.'),
    ('duration', 'courses.duration', 'hybrid_manual_preferred', true, true, 'Human-readable duration. Required for publication; placeholders such as Consultar are treated as missing.'),
    ('price_pen', 'courses.price_pen', 'hybrid_manual_preferred', false, true, 'Numeric price in PEN when available.'),
    ('price_status', 'courses.price_status', 'hybrid_manual_preferred', false, true, 'Display status for unavailable or consultative pricing.'),
    ('description_long', 'courses.description_long', 'hybrid_manual_preferred', false, true, 'Long-form public course description.'),
    ('syllabus', 'courses.syllabus', 'hybrid_manual_preferred', false, true, 'Public syllabus or curriculum summary.'),
    ('target_audience', 'courses.target_audience', 'hybrid_manual_preferred', false, true, 'Audience profile for the program.'),
    ('requirements', 'courses.requirements', 'hybrid_manual_preferred', false, true, 'Admission or participation requirements.'),
    ('certification', 'courses.certification', 'hybrid_manual_preferred', false, true, 'Certification or credential awarded.'),
    ('benefits', 'courses.benefits', 'hybrid_manual_preferred', false, true, 'Public benefits or outcomes.'),
    ('objectives', 'courses.objectives', 'hybrid_manual_preferred', false, true, 'Learning objectives.'),
    ('start_date', 'courses.start_date', 'hybrid_manual_preferred', false, true, 'Structured start date when confirmed.'),
    ('start_date_text', 'courses.start_date_text', 'hybrid_manual_preferred', false, true, 'Human-readable start date fallback.'),
    ('course_type', 'courses.course_type', 'pipeline_owned', false, true, 'Course type used for ranking and ROI adjustments.'),
    ('brochure_url', 'courses.brochure_url', 'pipeline_owned', false, true, 'Public brochure URL when available.'),
    ('expected_monthly_salary', 'courses.expected_monthly_salary', 'computed', false, true, 'Computed salary estimate for ROI display.'),
    ('seniority_level', 'courses.seniority_level', 'computed', false, true, 'Seniority band used in ROI calculations.'),
    ('roi_months', 'courses.roi_months', 'computed', false, true, 'Computed estimated months to recover investment.'),
    ('view_count', 'courses.view_count', 'computed', false, true, 'Public engagement counter.'),
    ('comparison_count', 'courses.comparison_count', 'computed', false, true, 'Public comparison counter.'),
    ('editorial_status', 'course_editorial_state.editorial_status', 'manual_owned', true, false, 'Private editorial workflow state. Publication requires explicit manual action.'),
    ('quality_status', 'course_editorial_state.quality_status', 'computed', true, false, 'Private quality gate computed from required field completeness.'),
    ('missing_fields', 'course_editorial_state.missing_fields', 'computed', false, false, 'Private list of required fields still missing.'),
    ('field_sources', 'course_editorial_state.field_sources', 'computed', false, false, 'Private provenance map by field.'),
    ('field_timestamps', 'course_editorial_state.field_timestamps', 'computed', false, false, 'Private timestamp map by field.'),
    ('manual_overrides', 'course_editorial_state.manual_overrides', 'manual_owned', false, false, 'Private editorial override payload.'),
    ('manual_start_date', 'course_editorial_state.manual_start_date', 'manual_owned', false, false, 'Private structured start date override.'),
    ('is_sponsored', 'course_editorial_state.is_sponsored', 'manual_owned', false, false, 'Private sponsorship flag.'),
    ('sponsored_priority', 'course_editorial_state.sponsored_priority', 'manual_owned', false, false, 'Private sponsorship ordering weight.'),
    ('sponsorship_label', 'course_editorial_state.sponsorship_label', 'manual_owned', false, false, 'Private label for sponsored placements.'),
    ('lead_cta_enabled', 'course_editorial_state.lead_cta_enabled', 'manual_owned', false, false, 'Private flag controlling lead CTA availability.'),
    ('availability_status', 'course_editorial_state.availability_status', 'computed', true, false, 'Private availability gate. Public view only exposes available courses.'),
    ('published_at', 'course_editorial_state.published_at', 'manual_owned', true, false, 'Private publication timestamp required when published.'),
    ('archived_at', 'course_editorial_state.archived_at', 'manual_owned', false, false, 'Private archive timestamp required when archived.'),
    ('manual_updated_at', 'course_editorial_state.manual_updated_at', 'manual_owned', false, false, 'Private timestamp of last manual editorial update.'),
    ('manual_updated_by', 'course_editorial_state.manual_updated_by', 'manual_owned', true, false, 'Private actor reference required for publication.')
ON CONFLICT (field_key) DO UPDATE SET
    target_column = EXCLUDED.target_column,
    ownership = EXCLUDED.ownership,
    is_required_for_publish = EXCLUDED.is_required_for_publish,
    is_public = EXCLUDED.is_public,
    description = EXCLUDED.description,
    updated_at = now();
