-- Activate Universidad de Lima for the post-Fase-100 gated pipeline.

UPDATE public.institution_site_profiles
SET
    site_type = 'traditional_ssr',
    discovery_mode = 'hardcoded_urls',
    section_mode_map = '{"/pregrado/":"Presencial","/maestria/":"Presencial","/doctorado/":"Presencial","/idiomas/":"Presencial","/cursos-talleres/":"Remoto"}'::jsonb,
    section_course_type_map = '{"/pregrado/":"Pregrado","/maestria/":"Maestria","/doctorado/":"Doctorado","/idiomas/":"Curso","/cursos-talleres/":"Curso"}'::jsonb,
    section_keywords = '{"Perfil del egresado":"graduate_profile","Malla curricular":"curriculum_summary","Plan de estudios":"curriculum_summary","Requisitos":"requirements","Dirigido a":"target_audience","Inversion":"total_cost_est","Inversión":"total_cost_est","Inicio":"start_date","Duracion":"duration_text","Duración":"duration_text"}'::jsonb,
    field_defaults = '{"mode":"Presencial"}'::jsonb,
    title_prefix_removals = '["U. Lima | ","Universidad de Lima | ","ULIMA - "]'::jsonb,
    detail_wait_ms = 3000,
    price_regex = 'S/[\s]*[\d,.]+',
    duration_regex = '(\d+\.?\d*)\s*(meses|años|anos|ciclos|horas)',
    seed_urls = urls.seed_urls,
    notes = '102 seed URLs curated. Pipeline activated by 20260526_ulima_pipeline_activation.sql.',
    pipeline_ready = true,
    discovery_enabled = true,
    pipeline_enabled = true,
    production_enabled = true,
    updated_at = now()
FROM (
    SELECT jsonb_agg(url ORDER BY ord) AS seed_urls
    FROM (VALUES
        (1, 'https://www.ulima.edu.pe/pregrado/administracion'),
        (2, 'https://www.ulima.edu.pe/pregrado/comunicacion'),
        (3, 'https://www.ulima.edu.pe/pregrado/derecho'),
        (4, 'https://www.ulima.edu.pe/pregrado/ingenieria-ambiental'),
        (5, 'https://www.ulima.edu.pe/pregrado/ingenieria-industrial'),
        (6, 'https://www.ulima.edu.pe/pregrado/ingenieria-de-sistemas'),
        (7, 'https://www.ulima.edu.pe/pregrado/arquitectura'),
        (8, 'https://www.ulima.edu.pe/pregrado/contabilidad-y-finanzas'),
        (9, 'https://www.ulima.edu.pe/pregrado/economia'),
        (10, 'https://www.ulima.edu.pe/pregrado/ingenieria-civil'),
        (11, 'https://www.ulima.edu.pe/pregrado/ingenieria-mecatronica'),
        (12, 'https://www.ulima.edu.pe/pregrado/marketing'),
        (13, 'https://www.ulima.edu.pe/posgrado/maestria/macp'),
        (14, 'https://www.ulima.edu.pe/posgrado/maestria/mbf'),
        (15, 'https://www.ulima.edu.pe/posgrado/maestria/mcdn'),
        (16, 'https://www.ulima.edu.pe/posgrado/maestria/mcgc'),
        (17, 'https://www.ulima.edu.pe/posgrado/maestria/mde'),
        (18, 'https://www.ulima.edu.pe/posgrado/maestria/mdop'),
        (19, 'https://www.ulima.edu.pe/posgrado/maestria/mdie'),
        (20, 'https://www.ulima.edu.pe/posgrado/maestria/mgi'),
        (21, 'https://www.ulima.edu.pe/posgrado/maestria/mgc'),
        (22, 'https://www.ulima.edu.pe/posgrado/maestria/mid'),
        (23, 'https://www.ulima.edu.pe/posgrado/maestria/mlp'),
        (24, 'https://www.ulima.edu.pe/posgrado/maestria/mmgc'),
        (25, 'https://www.ulima.edu.pe/posgrado/maestria/mtpf'),
        (26, 'https://www.ulima.edu.pe/posgrado/maestria/mba'),
        (27, 'https://www.ulima.edu.pe/posgrado/doctorado/da'),
        (28, 'https://www.ulima.edu.pe/posgrado/doctorado/dc'),
        (29, 'https://www.ulima.edu.pe/posgrado/doctorado/dge'),
        (30, 'https://www.ulima.edu.pe/idiomas/programa-integral-ingles'),
        (31, 'https://www.ulima.edu.pe/idiomas/english-business'),
        (32, 'https://www.ulima.edu.pe/idiomas/english-media'),
        (33, 'https://www.ulima.edu.pe/idiomas/english-engineering'),
        (34, 'https://www.ulima.edu.pe/idiomas/extension-workshops'),
        (35, 'https://www.ulima.edu.pe/idiomas/intensive-graduation'),
        (36, 'https://www.ulima.edu.pe/idiomas/b2-first'),
        (37, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-comunicacion-marketing-politico'),
        (38, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-cultura-organizacional'),
        (39, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/vir-presentaciones-alto-impacto'),
        (40, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-alto-impacto-presentaciones'),
        (41, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-arbitraje'),
        (42, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-app'),
        (43, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-corporate-compliance'),
        (44, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-legaltech-ia-abogados'),
        (45, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-ley-contrataciones-estado'),
        (46, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/vir-obras-impuesto'),
        (47, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-obras-publicas'),
        (48, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/vir-resolucion-conflictos'),
        (49, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-gestion-compensacion-total'),
        (50, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-people-analytics'),
        (51, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-domina-tiempo'),
        (52, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-expresate-lidera'),
        (53, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-power-skills'),
        (54, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-soft-skills'),
        (55, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-liderazgo-alto-desempeno'),
        (56, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-analisis-fundamental'),
        (57, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-analisis-tecnico'),
        (58, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-elaboracion-presupuestos'),
        (59, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-finanzas-no-especialistas'),
        (60, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-gestion-tesoreria'),
        (61, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-gestion-riesgo-compliance'),
        (62, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-impuesto-renta'),
        (63, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-control-interno'),
        (64, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-niif'),
        (65, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-inversion-bolsa'),
        (66, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-python-aplicado-finanzas'),
        (67, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-fraude-auditoria-forense'),
        (68, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-bloomberg'),
        (69, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-construccion'),
        (70, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-marca-ia'),
        (71, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-growth-hacking'),
        (72, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-ia-marketing-digital'),
        (73, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-kam'),
        (74, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-negociacion-comercial'),
        (75, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/vir-marketing-digital'),
        (76, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-retail-category-management'),
        (77, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-social-media'),
        (78, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-ia-creadores-contenido'),
        (79, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-metodologias-agiles'),
        (80, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-direccion-supply-chain'),
        (81, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-gestion-proyectos'),
        (82, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/vir-mejora-rediseno-procesos'),
        (83, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-planeamiento-estrategico'),
        (84, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/vir-seguridad-salud-trabajo'),
        (85, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-future-thinking'),
        (86, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-arquitectura-soluciones-digitales'),
        (87, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-business-analytics'),
        (88, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-data-analytics'),
        (89, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-visualizacion-datos-power-bi'),
        (90, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-power-bi'),
        (91, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-excel'),
        (92, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-gobierno-datos'),
        (93, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-ia-generativa-negocios'),
        (94, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-modernizacion-aplicaciones'),
        (95, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-power-bi-desde-cero'),
        (96, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/cec-transformacion-digital'),
        (97, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-fundamentos-power-bi'),
        (98, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-ia-contenido-textual'),
        (99, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-talent-shift'),
        (100, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-transformacion-digital'),
        (101, 'https://www.ulima.edu.pe/educacion-ejecutiva/cursos-talleres/taller-sql-decisiones-negocio')
    ) AS ordered_urls(ord, url)
) AS urls
WHERE institution_id = (
    SELECT id FROM public.institutions WHERE slug = 'universidad-de-lima' LIMIT 1
);

UPDATE public.staging_raw
SET status = 'pending'
WHERE institution_id = (SELECT id FROM public.institutions WHERE slug = 'universidad-de-lima' LIMIT 1)
  AND status = 'discovered';
